name: "Deploy to Codigo Facilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigo-facilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binarios"
      - run: echo "publicar versi√≥n"
      